# Generated by Django 5.1.1 on 2024-10-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dose',
            old_name='url_to_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='content',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='updated_at',
        ),
    ]
