# Generated by Django 5.1.1 on 2024-10-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_url_to_image_dose_image_remove_dose_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dose',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
