# Generated by Django 5.1.1 on 2024-10-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_dose_content_alter_dose_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
