# Generated by Django 5.1.1 on 2024-10-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_dose_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
