# Generated by Django 5.1.1 on 2024-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_dose_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
