# Generated by Django 5.1.1 on 2024-10-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_dose_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dose',
            name='author',
        ),
    ]
