# Generated by Django 5.1.1 on 2024-10-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_dose_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
